gui:
  tabWidth: 4
  mouseEvents: false
  skipNoStagedFilesWarning: true
  showRandomTip: false
  showCommandLog: true
git:
  paging:
    #pager: "diff-so-fancy"
    useConfig: false
    externalDiffCommand: ""
  #commit:
  #  signOff: true
  merging:
    manualCommit: true
  log:
    showWholeGraph: true
quitOnTopLevelReturn: true
disableStartupPopups: true
customCommands: []
services: {}
notARepository: 'skip'
